name: blockfill
description: Block Fill by Wajiha - 100% free fun game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  shared_preferences: ^2.5.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla.ttf
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab-Regular.ttf
        - asset: assets/fonts/ZillaSlab-Bold.ttf
          weight: 700
